import { RouteRecordRaw } from "vue-router";

const routes: RouteRecordRaw[] = [{
    path: "midone",
    component: () => import("./views/layout.vue"),
    children: [
        { path: "dashboard-overview-1", component: () => import("./views/dashboard-overview-1/Main.vue") },
        { path: "dashboard-overview-2", component: () => import("./views/dashboard-overview-2/Main.vue") },
        { path: "dashboard-overview-3", component: () => import("./views/dashboard-overview-3/Main.vue") },
        { path: "dashboard-overview-4", component: () => import("./views/dashboard-overview-4/Main.vue") },
        { path: "inbox", component: () => import("./views/inbox/Main.vue") },
        { path: "file-manager", component: () => import("./views/file-manager/Main.vue") },
        { path: "point-of-sale", component: () => import("./views/point-of-sale/Main.vue") },
        { path: "chat", component: () => import("./views/chat/Main.vue") },
        { path: "post", component: () => import("./views/post/Main.vue") },
        { path: "calendar", component: () => import("./views/calendar/Main.vue") },
        { path: "crud-data-list", component: () => import("./views/crud-data-list/Main.vue") },
        { path: "crud-form", component: () => import("./views/crud-form/Main.vue") },
        { path: "users-layout-1", component: () => import("./views/users-layout-1/Main.vue") },
        { path: "users-layout-2", component: () => import("./views/users-layout-2/Main.vue") },
        { path: "users-layout-3", component: () => import("./views/users-layout-3/Main.vue") },
        { path: "profile-overview-1", component: () => import("./views/profile-overview-1/Main.vue") },
        { path: "profile-overview-2", component: () => import("./views/profile-overview-2/Main.vue") },
        { path: "profile-overview-3", component: () => import("./views/profile-overview-3/Main.vue") },
        { path: "wizard-layout-1", component: () => import("./views/wizard-layout-1/Main.vue") },
        { path: "wizard-layout-2", component: () => import("./views/wizard-layout-2/Main.vue") },
        { path: "wizard-layout-3", component: () => import("./views/wizard-layout-3/Main.vue") },
        { path: "blog-layout-1", component: () => import("./views/blog-layout-1/Main.vue") },
        { path: "blog-layout-2", component: () => import("./views/blog-layout-2/Main.vue") },
        { path: "blog-layout-3", component: () => import("./views/blog-layout-3/Main.vue") },
        { path: "pricing-layout-1", component: () => import("./views/pricing-layout-1/Main.vue") },
        { path: "pricing-layout-2", component: () => import("./views/pricing-layout-2/Main.vue") },
        { path: "invoice-layout-1", component: () => import("./views/invoice-layout-1/Main.vue") },
        { path: "invoice-layout-2", component: () => import("./views/invoice-layout-2/Main.vue") },
        { path: "faq-layout-1", component: () => import("./views/faq-layout-1/Main.vue") },
        { path: "faq-layout-2", component: () => import("./views/faq-layout-2/Main.vue") },
        { path: "faq-layout-3", component: () => import("./views/faq-layout-3/Main.vue") },
        { path: "update-profile", component: () => import("./views/update-profile/Main.vue") },
        { path: "change-password", component: () => import("./views/change-password/Main.vue") },
        { path: "regular-table", component: () => import("./views/regular-table/Main.vue") },
        { path: "modal", component: () => import("./views/modal/Main.vue") },
        { path: "slide-over", component: () => import("./views/slide-over/Main.vue") },
        { path: "notification", component: () => import("./views/notification/Main.vue") },
        { path: "tab", component: () => import("./views/tab/Main.vue") },
        { path: "accordion", component: () => import("./views/accordion/Main.vue") },
        { path: "button", component: () => import("./views/button/Main.vue") },
        { path: "alert", component: () => import("./views/alert/Main.vue") },
        { path: "progress-bar", component: () => import("./views/progress-bar/Main.vue") },
        { path: "tooltip", component: () => import("./views/tooltip/Main.vue") },
        { path: "dropdown", component: () => import("./views/dropdown/Main.vue") },
        { path: "typography", component: () => import("./views/typography/Main.vue") },
        { path: "icon", component: () => import("./views/icon/Main.vue") },
        { path: "loading-icon", component: () => import("./views/loading-icon/Main.vue") },
        { path: "regular-form", component: () => import("./views/regular-form/Main.vue") },
        { path: "datepicker", component: () => import("./views/datepicker/Main.vue") },
        { path: "tom-select", component: () => import("./views/tom-select/Main.vue") },
        { path: "file-upload", component: () => import("./views/file-upload/Main.vue") },
        { path: "wysiwyg-editor", component: () => import("./views/wysiwg-editor/Main.vue") },
        { path: "validation", component: () => import("./views/validation/Main.vue") },
        { path: "chart", component: () => import("./views/chart/Main.vue") },
        { path: "slider", component: () => import("./views/slider/Main.vue") },
        { path: "image-zoom", component: () => import("./views/image-zoom/Main.vue") },
    ]
}];

export default routes;