<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>EmptyProject.Core</RootNamespace>
    <AssemblyName>EmptyProject.Core</AssemblyName>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <FileVersion>1.0.0</FileVersion>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <WarningLevel>4</WarningLevel>
    <OutputPath>..\..\..\binary\Debug\</OutputPath>
    <DocumentationFile></DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\..\binary\Release\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EFCore.BulkExtensions" Version="8.0.1" />
    <PackageReference Include="libphonenumber-csharp" Version="8.13.29" />
    <PackageReference Include="LinqKit.Microsoft.EntityFrameworkCore" Version="8.1.5" />
    <PackageReference Include="NPOI" Version="2.6.2" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
    <PackageReference Include="FluentFTP" Version="49.0.2" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Data\Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="J.Framework.Business">
      <HintPath>..\Libraries\J.Framework.Business.dll</HintPath>
    </Reference>
    <Reference Include="J.Framework.Content">
      <HintPath>..\Libraries\J.Framework.Content.dll</HintPath>
    </Reference>
    <Reference Include="J.Framework.Core">
      <HintPath>..\Libraries\J.Framework.Core.dll</HintPath>
    </Reference>
    <Reference Include="J.Framework.EntityFrameworkCore">
      <HintPath>..\Libraries\J.Framework.EntityFrameworkCore.dll</HintPath>
    </Reference>
    <Reference Include="J.Framework.Manufacture">
      <HintPath>..\Libraries\J.Framework.Manufacture.dll</HintPath>
    </Reference>
    <Reference Include="J.Framework">
      <HintPath>..\Libraries\J.Framework.dll</HintPath>
    </Reference>
    <Reference Include="J.Framework.Streaming">
      <HintPath>..\Libraries\J.Framework.Streaming.dll</HintPath>
    </Reference>
    <Reference Include="J.Framework.Web">
      <HintPath>..\Libraries\J.Framework.Web.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Remove="J.Framework.Business" />
    <None Remove="J.Framework.Content" />
    <None Remove="J.Framework.Core" />
    <None Remove="J.Framework.EntityFrameworkCore" />
    <None Remove="J.Framework.Manufacture" />
    <None Remove="J.Framework" />
    <None Remove="System.Data.SqlClient" />
    <None Remove="Streaming\" />
    <None Remove="Streaming\Actions\" />
    <None Remove="Streaming\Models\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Streaming\" />
    <Folder Include="Streaming\Actions\" />
    <Folder Include="Streaming\Models\" />
  </ItemGroup>
</Project>
